services:
  postgres:
    image: postgres:15.2
    container_name: tinode-postgres-dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tinode
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - tinode-pg-data:/var/lib/postgresql/data

volumes:
  tinode-pg-data:
