# Accept the Go version for the image to be set as a build argument.
ARG GO_VERSION=1.16

# Execute the build using an alpine linux environment so that it will execute properly in the final environment
FROM golang:${GO_VERSION}-alpine AS builder

ENV CGO_ENABLED=0
ENV GO111MODULE=on
ENV GOFLAGS=-mod=vendor

# Create the user and group files that will be used in the running container to
# run the process as an unprivileged user.
RUN mkdir /user && \
    echo 'nobody:x:65534:65534:nobody:/:' > /user/passwd && \
    echo 'nobody:x:65534:' > /user/group

# Install the Certificate-Authority certificates for the app to be able to make
# calls to HTTPS endpoints.
# Git is required for fetching the dependencies.
RUN apk add ca-certificates

# Set a directory to contain the go app to be compiled (this directory will work for go apps making use of go modules as long as go 1.13+ is used)
RUN mkdir -p /go/src/mgi-vn/chat
WORKDIR /go/src/mgi-vn/chat

COPY . .
RUN mkdir -p /dist
RUN mkdir -p /dist/templ
RUN mkdir -p /dist/queue

RUN go build \
    -installsuffix 'static' \
    -tags "mongodb" \
    -o /dist/chat /go/src/mgi-vn/chat/server

# RUN go get github.com/mitchellh/gox
# RUN gox -osarch="linux/amd64" \
#         -ldflags "-s -w -X main.buildstamp=`git describe --tags`" \
#         -tags "mongodb" -output /dist /go/src/mgi-vn/chat > /dev/null

# RUN cp entrypoint.sh /dist/
RUN cp server/tinode.conf /dist/
RUN cp server/.env-dev /dist/.env
RUN cp server/templ/*.templ /dist/templ/
RUN cp server/queue/*.json /dist/queue/

# Final stage: the running container.
FROM alpine AS final

# Import the user and group files from the first stage.
COPY --from=builder /user/group /user/passwd /etc/

# Import the Certificate-Authority certificates for enabling HTTPS.
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Import the compiled executable from the first stage.
COPY --from=builder /dist /
RUN mkdir -p /uploads

# Make scripts runnable
# RUN chmod +x entrypoint.sh

# Import the compiled grpc-health-probe from the first stage
# COPY --from=builder /go/bin/grpc-health-probe /usr/bin/local/grpc-health-probe

# Perform any further action as an unprivileged user.
USER nobody:nobody

# Generate config from template and run the server.
# ENTRYPOINT ./entrypoint.sh
ENTRYPOINT ["/chat", "-static_data", "-"]
# EXPOSE 6060 6080

# HTTP, gRPC, cluster ports
EXPOSE 6060 16060 12000-12003