apiVersion: v1
kind: ConfigMap
metadata:
  name: tinode-config-postgres
  namespace: default
  labels:
    app.kubernetes.io/name: tinode
data:
  tinode.conf: |
    {
      "listen": ":6060",
      "grpc_listen": ":16060",
      "cache_control": 39600,
      "api_key_salt": "T713/rYYgW7g4m3vG6zGRh7+FM1t0T8j13koXScOAj4=",
      "max_message_size": 4194304,
      "max_subscriber_count": 32,
      "max_tag_count": 16,
      "use_x_forwarded_for": true,
      "expvar": "/debug/vars",
      "server_status": "/stats/status/",
      "tls": {
        "enabled": false
      },
      "auth_config": {
        "logical_names": ["basic:login-basic"],
        "basic": {
          "add_to_tags": true,
          "min_login_length": 4,
          "min_password_length": 6
        },
        "token": {
          "expire_in": 1209600,
          "serial_num": 1,
          "key": "wfaY2RgF2S1OQI/ZlK+LSrp1KB2jwAdGAIHQ7JZn+Kc="
        }
      },
      "store_config": {
        "use_adapter": "postgres",
        "uid_key": "la6YsO+bNX/+XIkOqc5Svw==",
        "adapters": {
          "postgres": {
            "dsn": "postgresql://postgres:postgres@postgres:5432/tinode?sslmode=disable&connect_timeout=10"
          }
        }
      },
      "cluster_config": {
        "self": "",
        "discovery": {
          "mode": "kubernetes",
          "kubernetes": {
            "namespace": "",
            "service": "tinode-headless",
            "port_name": "cluster",
            "label_selector": ""
          }
        }
      }
    }
